### ISSUE TITLE
Create scraper package, write scrapers and create [scheduled] tasks

### ISSUE THREAD

**Issue by wfdd** [openpatata/openpatata#16]
At a first stage, scrapers should be written for:

* new bills (http://www2.parliament.cy/parliamentgr/005_02.htm)
* plenary sittings (http://www.parliament.cy/easyconsole.cfm/id/290)
* committee reports (http://www.parliament.cy/easyconsole.cfm/id/220)
* questions and answers (http://www2.parliament.cy/parliamentgr/008_02.htm)

**Comment by akuckartz** [comment]
There already exist a few scraper projects with similar aims for other countries. I suggest to collaborate with them.

**Comment by wfdd** [comment]
Hi Andreas

What would the benefit over using a scraping framework, like [scrapy](http://scrapy.org/), be?

**Comment by akuckartz** [comment]
Most if not all scraper projects use a scraping framework or library. And they might have already thought about or implemented features you will need or like. In other words: you might benefit from not reimplementing wheels. On the other hand you would have to spend some time reviewing what others have done.

**Comment by wfdd** [comment]
The bulk of the work's in parsing the data; that is, in applying filters to text. These filters will evidently need to be different. Though there might be a few things that'll be of use to us in existing scrapers, I think it'd be a fool's errand to build on top of one of them.

P.S. Thanks for your interest!

**Comment by wfdd** [comment]
Started; see [openpatata/openpatata-scrapers](http://github.com/openpatata/openpatata-scrapers).
